version: "3"
services:
  api:
    build:
      context: ./src
      dockerfile: Dockerfile
    volumes:
      - ./src:/application/src
      - ./database:/database
    ports:
      - 3000:3000
    restart: always